name: Count entries
on:
  push:
    branches:
      - master
      
jobs:
  create_gif:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: count
        run: python3 tools/count_entries.py
      - name: calculate language stats
        run: python3 tools/calculate_languages.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update readme count
          file_pattern: '*.md'
